// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contributor struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	FirstName pgtype.Text
	LastName  pgtype.Text
	Email     pgtype.Text
}

type GitRepo struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Url       pgtype.Text
}

type Language struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type RefreshToken struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	TokenHash string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UserID    pgtype.Int8
}

type Snippet struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Title       pgtype.Text
	Code        pgtype.Text
	ProjectUrl  pgtype.Text
	GitFilePath pgtype.Text
	GitVersion  pgtype.Text
	GitRepoID   pgtype.Int8
	LanguageID  pgtype.Int8
	UserID      pgtype.Int8
}

type SnippetContributor struct {
	SnippetID     int64
	ContributorID int64
}

type SnippetTag struct {
	SnippetID int64
	TagID     int64
}

type Tag struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type User struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Username     string
	Email        string
	PasswordHash string
}
