// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contributor struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	FirstName pgtype.Text
	LastName  pgtype.Text
	Email     pgtype.Text
}

type Language struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}

type Script struct {
	ID         uuid.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Title      pgtype.Text
	Code       pgtype.Text
	ProjectUrl pgtype.Text
	LanguageID pgtype.UUID
}

type ScriptContributor struct {
	ScriptID      uuid.UUID
	ContributorID uuid.UUID
}

type ScriptTag struct {
	ScriptID uuid.UUID
	TagID    uuid.UUID
}

type Tag struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      pgtype.Text
}
