// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLanguages = `-- name: CountLanguages :one
SELECT COUNT(*) FROM languages
`

func (q *Queries) CountLanguages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLanguages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTags = `-- name: CountTags :one
SELECT COUNT(*) FROM tags
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContributorsExcept = `-- name: DeleteContributorsExcept :exec
DELETE FROM contributors WHERE NOT (id = ANY($1::UUID[]))
`

func (q *Queries) DeleteContributorsExcept(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContributorsExcept, ids)
	return err
}

const deleteLanguagesExcept = `-- name: DeleteLanguagesExcept :exec
DELETE FROM languages WHERE NOT (id = ANY($1::UUID[]))
`

func (q *Queries) DeleteLanguagesExcept(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLanguagesExcept, ids)
	return err
}

const deleteScriptsBefore = `-- name: DeleteScriptsBefore :exec
DELETE FROM scripts WHERE created_at < $1
`

func (q *Queries) DeleteScriptsBefore(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteScriptsBefore, createdAt)
	return err
}

const deleteTagsExcept = `-- name: DeleteTagsExcept :exec
DELETE FROM tags WHERE NOT (id = ANY($1::UUID[]))
`

func (q *Queries) DeleteTagsExcept(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagsExcept, ids)
	return err
}

const getContributorIDByEmail = `-- name: GetContributorIDByEmail :one
SELECT id FROM contributors WHERE email=$1
`

func (q *Queries) GetContributorIDByEmail(ctx context.Context, email pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getContributorIDByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getLanguageIDByName = `-- name: GetLanguageIDByName :one
SELECT id FROM languages WHERE name=$1
`

func (q *Queries) GetLanguageIDByName(ctx context.Context, name pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLanguageIDByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getScriptIDByTitle = `-- name: GetScriptIDByTitle :one
SELECT id FROM scripts WHERE title=$1
`

func (q *Queries) GetScriptIDByTitle(ctx context.Context, title pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getScriptIDByTitle, title)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTagIDByName = `-- name: GetTagIDByName :one
SELECT id FROM tags WHERE name=$1
`

func (q *Queries) GetTagIDByName(ctx context.Context, name pgtype.Text) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTagIDByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const linkScriptContributor = `-- name: LinkScriptContributor :exec
INSERT INTO script_contributors (script_id, contributor_id) VALUES($1, $2) ON CONFLICT (script_id, contributor_id) DO NOTHING
`

type LinkScriptContributorParams struct {
	ScriptID      uuid.UUID
	ContributorID uuid.UUID
}

func (q *Queries) LinkScriptContributor(ctx context.Context, arg LinkScriptContributorParams) error {
	_, err := q.db.Exec(ctx, linkScriptContributor, arg.ScriptID, arg.ContributorID)
	return err
}

const linkScriptTag = `-- name: LinkScriptTag :exec
INSERT INTO script_tags (script_id, tag_id) VALUES($1, $2) ON CONFLICT (script_id, tag_id) DO NOTHING
`

type LinkScriptTagParams struct {
	ScriptID uuid.UUID
	TagID    uuid.UUID
}

func (q *Queries) LinkScriptTag(ctx context.Context, arg LinkScriptTagParams) error {
	_, err := q.db.Exec(ctx, linkScriptTag, arg.ScriptID, arg.TagID)
	return err
}

const listContributors = `-- name: ListContributors :many

SELECT id, created_at, updated_at, first_name, last_name, email FROM contributors OFFSET $1 LIMIT $2
`

type ListContributorsParams struct {
	Offset int32
	Limit  int32
}

// Contributors
func (q *Queries) ListContributors(ctx context.Context, arg ListContributorsParams) ([]Contributor, error) {
	rows, err := q.db.Query(ctx, listContributors, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contributor
	for rows.Next() {
		var i Contributor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguages = `-- name: ListLanguages :many

SELECT id, created_at, updated_at, name FROM languages OFFSET $1 LIMIT $2
`

type ListLanguagesParams struct {
	Offset int32
	Limit  int32
}

// Languages
func (q *Queries) ListLanguages(ctx context.Context, arg ListLanguagesParams) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedContributorIDs = `-- name: ListLinkedContributorIDs :many
SELECT DISTINCT(contributor_id) FROM script_contributors
`

func (q *Queries) ListLinkedContributorIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLinkedContributorIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var contributor_id uuid.UUID
		if err := rows.Scan(&contributor_id); err != nil {
			return nil, err
		}
		items = append(items, contributor_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedTagIDs = `-- name: ListLinkedTagIDs :many
SELECT DISTINCT(tag_id) FROM script_tags
`

func (q *Queries) ListLinkedTagIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLinkedTagIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tag_id uuid.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many

SELECT id, created_at, updated_at, name FROM tags OFFSET $1 LIMIT $2
`

type ListTagsParams struct {
	Offset int32
	Limit  int32
}

// Tags
func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedLanguageIDs = `-- name: ListUsedLanguageIDs :many
SELECT DISTINCT(language_id) FROM scripts
`

func (q *Queries) ListUsedLanguageIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUsedLanguageIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var language_id pgtype.UUID
		if err := rows.Scan(&language_id); err != nil {
			return nil, err
		}
		items = append(items, language_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContributor = `-- name: UpsertContributor :exec
INSERT INTO contributors (first_name, last_name, email) VALUES($1, $2, $3) ON CONFLICT (email) DO NOTHING
`

type UpsertContributorParams struct {
	FirstName pgtype.Text
	LastName  pgtype.Text
	Email     pgtype.Text
}

func (q *Queries) UpsertContributor(ctx context.Context, arg UpsertContributorParams) error {
	_, err := q.db.Exec(ctx, upsertContributor, arg.FirstName, arg.LastName, arg.Email)
	return err
}

const upsertLanguage = `-- name: UpsertLanguage :exec
INSERT INTO languages (name) VALUES($1) ON CONFLICT (name) DO NOTHING
`

func (q *Queries) UpsertLanguage(ctx context.Context, name pgtype.Text) error {
	_, err := q.db.Exec(ctx, upsertLanguage, name)
	return err
}

const upsertScript = `-- name: UpsertScript :exec

INSERT INTO scripts (title, code, project_url, language_id, created_at) VALUES($1, $2, $3, $4, $5)
ON CONFLICT (title) DO UPDATE SET created_at = EXCLUDED.created_at
`

type UpsertScriptParams struct {
	Title      pgtype.Text
	Code       pgtype.Text
	ProjectUrl pgtype.Text
	LanguageID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

// Scripts
func (q *Queries) UpsertScript(ctx context.Context, arg UpsertScriptParams) error {
	_, err := q.db.Exec(ctx, upsertScript,
		arg.Title,
		arg.Code,
		arg.ProjectUrl,
		arg.LanguageID,
		arg.CreatedAt,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (name) VALUES($1) ON CONFLICT (name) DO NOTHING
`

func (q *Queries) UpsertTag(ctx context.Context, name pgtype.Text) error {
	_, err := q.db.Exec(ctx, upsertTag, name)
	return err
}
